version: '3.3'

networks:
  evolution-net:
    driver: bridge

services:
  api:
    container_name: evolution_api
    image: evolution/api:local
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - ./Docker/.env
    command: ['node', './dist/src/main.js']
    networks:
      - evolution-net
    expose:
      - 8080

volumes:
  evolution_instances:
  evolution_store: