version: '3.3'

networks:
  evolution-net:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - evolution_mongodb_data:/data/db
      - evolution_mongodb_configdb:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - evolution-net
    expose:
      - 27017

volumes:
  evolution_mongodb_data:
  evolution_mongodb_configdb: